apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
  tenants:
    mode: openshift-logging
  managementState: Managed
  limits:
    global:
      queries:
        queryTimeout: 3m
      retention:
        days: 1
  storage:
    schemas:
      - effectiveDate: '2020-10-11'
        version: v13
    secret:
      name: minio-secret-lokistack
      type: s3
  hashRing:
    type: memberlist
  size: 1x.demo
  storageClassName: ${storageClassName}

