apiVersion: v1
kind: Service
metadata:
  name: postgresdb

spec:
  type: ExternalName
  externalName: postgres.${PROJECT}.svc.cluster.local

---
apiVersion: v1
kind: Service
metadata:
  name: flights
spec:
  type: ExternalName
  externalName: flight-information-service.${PROJECT}.svc.cluster.local